return {
	--[[ -- 基础依赖 ]]
	--[[ { import = "plugins.plenary" }, ]]
	--[[ { import = "plugins.coverage" }, ]]
	--[[ -- 其他插件 ]]
	--[[ { import = "plugins.colourscheme" }, -- 色彩主题 ]]
	--[[ { import = "plugins.lualine" }, -- 状态栏 ]]
	--[[ { import = "plugins.lsp" }, -- lsp ]]
	--[[ { import = "plugins.gitsigns" }, -- git状态栏显示 ]]
	--[[ { import = "plugins.easymotion" }, -- 文件快速跳转 ]]
	--[[ { import = "plugins.nvim-telescope" }, -- 文件模糊查找 ]]
	--[[ { import = "plugins.comment" }, -- 代码注释 ]]
	--[[ { import = "plugins.stevearc" }, -- 格式化引擎核心 ]]
	--[[ { import = "plugins.treesitter" }, -- 语法高亮增强 ]]
	--[[ { import = "plugins.akinsho" }, -- 集成终端 ]]
	--[[ { import = "plugins.mini-nvim" }, -- mini.nvim ]]
	--[[ { import = "plugins.alpha-nvim" }, -- 自定义启动页面 ]]
	--[[ { import = "plugins.cph-nvim" }, -- CPH ]]
}
